TRAD-210 swap with route specification
bloXroute-Labs/solana-trader-proto pull request #24
Opened 2022-10-03 16:54 UTC by tinystarinagalaxy

2022-10-04 19:41 UTC, aspin commented on proto/api.proto
> +  rpc PostMultiRouteTradeSwap(MultiRouteTradeSwapRequest) returns (MultiRouteTradeSwapResponse) {
naming: I don't think `Multi` should be part of this name. This is a swap with a route specification, and it's valid if the user decides to give a route specification of size 1. So I think `PostRouteTradeSwap` or `PostRouteSwap` would be better

2022-10-04 19:41 UTC, aspin commented on proto/api.proto
> +  string middleToken = 4;
does middle token need to be made to the original request?

2022-10-05 19:31 UTC, tinystarinagalaxy commented on proto/api.proto
> +  rpc PostMultiRouteTradeSwap(MultiRouteTradeSwapRequest) returns (MultiRouteTradeSwapResponse) {
ok done.

2022-10-05 19:31 UTC, tinystarinagalaxy commented on proto/api.proto
> +  string middleToken = 4;
no, removed it

2022-10-06 15:21 UTC, aspin approved these changes

2022-10-08 03:00 UTC, aspin requested changes
see changes in https://github.com/bloXroute-Labs/solana-trader-proto/pull/29/files#diff-ecf0878b123623e280a40f3e3d75af4267f11cfe7138753e671654c0ba05f228R264

2022-10-08 03:00 UTC, aspin commented on proto/api.proto
> +      get: "/api/v1/amm/route-trade-swap"
endpoint needs to be updated: should be `/api/v1/trade/route-swap`

2022-10-08 03:00 UTC, aspin commented on proto/api.proto
> +      tags: "AMMs";
`"Trade/AMM"`

2022-10-08 03:00 UTC, aspin commented on proto/api.proto
> +      description: "routes swap(s) from supported amms";
description for consistency: "Generates an unsigned transaction object for the AMM swap on the specified route"

summary for consistency: "Unsigned AMM swap transaction along route"

2022-10-11 21:32 UTC, tinystarinagalaxy commented on proto/api.proto
> +      get: "/api/v1/amm/route-trade-swap"
done

2022-10-11 21:33 UTC, tinystarinagalaxy commented on proto/api.proto
> +      tags: "AMMs";
done

2022-10-11 21:33 UTC, tinystarinagalaxy commented on proto/api.proto
> +      description: "routes swap(s) from supported amms";
done

2022-10-12 15:42 UTC, aspin requested changes

2022-10-12 15:42 UTC, aspin commented on proto/api.proto
> +      tags: "Trade/AMM";
actually should be `["Trade", "AMM"]` now, after some review changes on my end

2022-10-12 15:42 UTC, aspin commented on proto/api.proto
> +      get: "/api/v1/amm/route-swap"
endpoint needs to be `/api/v1/trade/route-swap`

2022-10-12 16:26 UTC, tinystarinagalaxy commented on proto/api.proto
> +      get: "/api/v1/amm/route-swap"
done

2022-10-12 16:40 UTC, aspin commented on proto/api.proto
> +      tags: "Trade/AMM";
bump

2022-10-12 16:45 UTC, aspin commented
bump on the tags comment

2022-10-12 16:50 UTC, tinystarinagalaxy commented on proto/api.proto
> +      tags: "Trade/AMM";
done

2022-10-12 16:52 UTC, aspin approved these changes

2022-10-12 17:02 UTC, merged