TRAD-259 Organization
bloXroute-Labs/solana-trader-proto pull request #29
Opened 2022-10-08 02:58 UTC by aspin

reorganizes endpoint after discussion with Daniel. Highlights:
 - get rid of `/amm` section
 - instead, move everything into either `/market` or `/trade`
 - add some general sectioning in swagger to indicate AMMs vs Orderbooks

2022-10-08 03:39 UTC, kdonthi requested changes
I am getting a bit confused by these tags.

Could we do slightly different tags where the first part is [Amm, Orderbook] and the second part is [Info, Trade]?

2022-10-09 16:38 UTC, aspin commented
> I am getting a bit confused by these tags.
> 
> Could we do slightly different tags where the first part is [Amm, Orderbook] and the second part is [Info, Trade]?

see https://github.com/bloXroute-Labs/solana-trader-api/pull/223#issuecomment-1272208449
I'm not sure if it's possible to do multiple tags. Let me see...

Even if it is it'd result in endpoints in multiple sections in Swagger, which I don't think is very intuitive

2022-10-10 18:11 UTC, aspin commented
Spent some time on this. Needed to manually generate a global tag list, but got it all working.

2022-10-10 18:19 UTC, aspin commented
<img width="1456" alt="Screen Shot 2022-10-10 at 1 19 04 PM" src="https://user-images.githubusercontent.com/5728920/194929502-6986a709-16b1-437f-a7bd-ecd48edfd1da.png">
looks like this now. Some endpoints will be in multiple sections

2022-10-10 22:22 UTC, merged