Compiling protobus for clients app in this project
bloXroute-Labs/solana-trader-proto pull request #49
Opened 2022-11-18 18:54 UTC by tinystarinagalaxy

2022-11-18 20:18 UTC, aspin commented on proto/ffi/ffi.proto
> +syntax = "proto3";
can we not move the FFI proto files here? They don't really belong in this repo. I know they do depend on `api.proto`, but it'd be best to see if we could keep the FFI generated files out of here.

2022-11-22 16:41 UTC, tinystarinagalaxy commented on proto/ffi/ffi.proto
> +syntax = "proto3";
hmm, in that case we have to duplicate ffi proto definitions. technically, ffi proto is part of api.proto as a dependency to some extent. so its ok to keep all proto in one place.

2022-11-22 18:56 UTC, tinystarinagalaxy commented on proto/ffi/ffi.proto
> +syntax = "proto3";
on 2nd thoughts,  moved the common stuff to common.proto and kept ffi.proto in solana-trader-api.

2022-11-28 15:30 UTC, aspin approved these changes

2022-11-28 15:33 UTC, aspin commented on proto/api.proto
> +option go_package = "github.com/bloXroute-Labs/solana-trader-proto/proto/api";
should we actually make this `github.com/bloXroute-Labs/solana-trader-proto/api`? otherwise there's a tiny bit of redundancy in teh package name

2022-11-28 15:33 UTC, aspin commented on proto/common.proto
> +option go_package = "github.com/bloXroute-Labs/solana-trader-proto/proto/common";
same here, `github.com/bloXroute-Labs/solana-trader-proto/common`

2022-11-28 15:35 UTC, aspin requested changes

2022-11-28 15:35 UTC, aspin commented on Makefile
> +proto-docker-build-go:
I think some of these `Dockerfile-go` paths don't exist. Probably fine to copy over the docker files from api repo?

2022-11-28 15:35 UTC, aspin commented on Makefile
> +proto-docker-build-go:
`Dockerfile-js` too

2022-11-28 15:35 UTC, tinystarinagalaxy commented on proto/api.proto
> +option go_package = "github.com/bloXroute-Labs/solana-trader-proto/proto/api";
done

2022-11-28 15:35 UTC, tinystarinagalaxy commented on proto/common.proto
> +option go_package = "github.com/bloXroute-Labs/solana-trader-proto/proto/common";
done

2022-11-28 15:38 UTC, tinystarinagalaxy commented on Makefile
> +proto-docker-build-go:
i copied over from api repo already. `Dockerfile-go` and `Dockerfile-js` definitions don't exist in api repo either

2022-11-28 15:46 UTC, tinystarinagalaxy commented on Makefile
> +proto-docker-build-go:
added them to proto directory

2022-11-28 16:53 UTC, aspin approved these changes

2022-11-28 19:26 UTC, merged