perp positions changes
bloXroute-Labs/solana-trader-proto pull request #63
Opened 2023-01-11 16:01 UTC by tinystarinagalaxy

2023-01-12 17:58 UTC, DimaCantemir approved these changes

2023-01-12 19:00 UTC, aspin requested changes

2023-01-12 19:00 UTC, aspin commented on proto/api.proto
> +      tags: ["Trade", "Universal"];
Think this should be Orderbook, not Universal? Also, probably worth adding a "Perp" tag too

2023-01-12 19:00 UTC, aspin commented on proto/api.proto
> +      tags: ["Trade", "Universal"];
same comment ehre

2023-01-12 19:00 UTC, aspin commented on proto/api.proto
> -  OT_IOC = 2; // immediate or cancel
don't think we want to delete these –– they're valid for Serum/Openbook I think

2023-01-12 19:00 UTC, aspin commented on proto/api.proto
> +message GetPerpPositionsRequest {
minor: can you have request + response right next to each other in the file? Bit of work to scroll down to find `GetPerpPositionsResponses`

2023-01-12 19:00 UTC, aspin commented on proto/api.proto
> +message GetCurrentPerpPosition {
naming: `PerpPosition`?

2023-01-12 19:00 UTC, aspin commented on proto/api.proto
> +  string positionSide = 6; // long, short
probably should define an enum here

2023-01-12 19:00 UTC, aspin commented on proto/api.proto
> -  OT_IOC = 2; // immediate or cancel
actually, whats with the duplication with common.proto?

2023-01-13 17:36 UTC, tinystarinagalaxy commented on proto/api.proto
> +      tags: ["Trade", "Universal"];
added "Perp", "Orderbook" tags

2023-01-13 17:36 UTC, tinystarinagalaxy commented on proto/api.proto
> +      tags: ["Trade", "Universal"];
added "Perp", "Orderbook" tags

2023-01-13 17:38 UTC, tinystarinagalaxy commented on proto/api.proto
> -  OT_IOC = 2; // immediate or cancel
yep, this is a leftover now. deleted this. moved OrderType to common.proto  and added new orderTypes.

2023-01-13 17:39 UTC, tinystarinagalaxy commented on proto/api.proto
> +message GetCurrentPerpPosition {
renamed

2023-01-13 17:40 UTC, tinystarinagalaxy commented on proto/api.proto
> +message GetPerpPositionsRequest {
moved

2023-01-13 17:41 UTC, tinystarinagalaxy commented on proto/api.proto
> +  string positionSide = 6; // long, short
already had common.PerpPositionSide, replaced string with common.PerpPositionSide

2023-01-13 18:00 UTC, aspin commented on proto/api.proto
> +      tags: ["Trade", "Orderbook"];
Perp tag here too

2023-01-13 18:00 UTC, aspin commented on proto/api.proto
> +      get: "/api/v1/trade/perp-positions"
`trade/perp/positions` I think

2023-01-13 18:00 UTC, aspin commented on proto/api.proto
> +      get: "/api/v1/trade/close-perp-positions"
`/trade/perp/close-positions` I think

2023-01-13 18:00 UTC, aspin commented on proto/api.proto
> +message GetCurrentPerpPosition {
I think also get rid of the `Get` in front of the name. This doesn't have to just be part of a `Get` requests and is a more general datatype

2023-01-13 18:00 UTC, aspin reviewed
couple more suggestions. good when these are done though

2023-01-13 21:15 UTC, aspin approved these changes
take a look at the last comment then LGTM

2023-01-13 21:15 UTC, aspin commented on proto/api.proto
> +message PerpPositionsResponse {
think you misunderstood my comment here. These messages should have the `Get` in front of it. `GetPerpPosition` (field #3 here) is the one that shouldn't

2023-01-13 21:15 UTC, aspin commented on proto/api.proto
> +message PerpPositionsResponse {
the messages that match the RPC method (e.g. `GetPerpPositions(PerpPositionsRequest)  returns (PerpPositionsResponse)`) should always have the `Get` prefix. It's jsut the data types within the `Request`/`Response` objects that should not

2023-01-13 21:20 UTC, aspin approved these changes

2023-01-13 21:28 UTC, tinystarinagalaxy commented on proto/api.proto
> +message PerpPositionsResponse {
fixed this

2023-01-13 21:39 UTC, merged